
[build]
  command = "npm run build"  # Adjust based on your client-side build script
  functions = "server-build"  # Directory where Netlify functions (server-side code) are built
  publish = "build"  # Adjust based on your client-side build output directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200